export const USER_TOKEN= 'USER_TOKEN';
export const AUTH_USER= 'AUTH_USER';
export const START_USER_AUTHENTICATION = 'START_USER_AUTHENTICATION';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAILURE = 'USER_AUTH_FAILURE';

export const START_USER_LOGOUT = 'START_USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';
